import { Injectable, inject } from '@angular/core';
import jsPDF from 'jspdf';
import { ContratoAdminDetalle, ContratoAdminListItem, ContratoInput, ContratoPdfData, ContratoListItem } from '../models';
import { ContratoRepository } from '../data/contrato.repository';
import { OfertaRepository } from '../data/oferta.repository';

// ── PDF label maps ────────────────────────────────────────────────────────────
const L: Record<string, Record<string, string>> = {
  es: {
    title:       'CONTRATO DE SERVICIOS',
    subtitle:    'Documento generado automáticamente',
    file:        'Expediente',
    date:        'Fecha de generación',
    parties:     'PARTES',
    client:      'CLIENTE',
    contractor:  'CONSTRUCTOR',
    phone:       'Teléfono',
    email:       'Correo',
    service:     'SERVICIO',
    serviceName: 'Tipo de servicio',
    description: 'Descripción',
    address:     'Dirección',
    country:     'CANADÁ',
    terms:       'CONDICIONES DEL CONTRATO',
    price:       'Precio total',
    start:       'Fecha de inicio propuesta',
    deadline:    'Plazo de ejecución',
    warranty:    'Garantía',
    weeks:       'sem.',
    years:       'año(s)',
    noWarranty:  'Sin garantía especificada',
    work:        'DESCRIPCIÓN DE LOS TRABAJOS',
    signatures:  'FIRMAS',
    clientSign:  'Firma del cliente',
    contractorSign: 'Firma del constructor',
    place:       'Lugar y fecha',
    generated:   'Documento generado por el sistema',
  },
  en: {
    title:       'SERVICE CONTRACT',
    subtitle:    'Automatically generated document',
    file:        'File',
    date:        'Generation date',
    parties:     'PARTIES',
    client:      'CLIENT',
    contractor:  'CONTRACTOR',
    phone:       'Phone',
    email:       'Email',
    service:     'SERVICE',
    serviceName: 'Service type',
    description: 'Description',
    address:     'Address',
    country:     'CANADA',
    terms:       'CONTRACT TERMS',
    price:       'Total price',
    start:       'Proposed start date',
    deadline:    'Execution period',
    warranty:    'Warranty',
    weeks:       'wks.',
    years:       'year(s)',
    noWarranty:  'No warranty specified',
    work:        'DESCRIPTION OF WORK',
    signatures:  'SIGNATURES',
    clientSign:  'Client signature',
    contractorSign: 'Contractor signature',
    place:       'Place and date',
    generated:   'Document generated by the system',
  },
  fr: {
    title:       'CONTRAT DE SERVICES',
    subtitle:    'Document généré automatiquement',
    file:        'Dossier',
    date:        'Date de génération',
    parties:     'PARTIES',
    client:      'CLIENT',
    contractor:  'CONSTRUCTEUR',
    phone:       'Téléphone',
    email:       'Courriel',
    service:     'SERVICE',
    serviceName: 'Type de service',
    description: 'Description',
    address:     'Adresse',
    country:     'CANADA',
    terms:       'CONDITIONS DU CONTRAT',
    price:       'Prix total',
    start:       'Date de début proposée',
    deadline:    "Délai d'exécution",
    warranty:    'Garantie',
    weeks:       'sem.',
    years:       'an(s)',
    noWarranty:  'Aucune garantie spécifiée',
    work:        'DESCRIPTION DES TRAVAUX',
    signatures:  'SIGNATURES',
    clientSign:  'Signature du client',
    contractorSign: 'Signature du constructeur',
    place:       'Lieu et date',
    generated:   'Document généré par le système',
  },
};

@Injectable({ providedIn: 'root' })
export class ContratoService {
  private contratoRepo = inject(ContratoRepository);
  private ofertaRepo   = inject(OfertaRepository);

  // ── Listar contratos del cliente ─────────────────────────────────────────

  async getMisContratos(clienteId: string): Promise<ContratoListItem[]> {
    const rows = await this.contratoRepo.findByClienteId(clienteId);
    return rows.map((c: any) => {
      const svc    = c.expediente?.servicio;
      const locArr = c.expediente?.localizacion;
      const loc    = Array.isArray(locArr) ? locArr[0] : locArr;
      const con    = c.constructor;
      const cli    = c.cliente;
      const ofe    = Array.isArray(c.oferta) ? c.oferta[0] : c.oferta;
      return {
        id:                 c.id,
        expediente_id:      c.expediente_id                  ?? '',
        expediente_numero:  c.expediente?.numero             ?? '—',
        servicio_nombre:    svc?.nombre_es                   ?? '—',
        servicio_nombre_en: svc?.nombre_en ?? svc?.nombre_es ?? '—',
        servicio_nombre_fr: svc?.nombre_fr ?? svc?.nombre_es ?? '—',
        servicio_desc:      svc?.descripcion_es              ?? '',
        servicio_desc_en:   svc?.descripcion_en              ?? '',
        servicio_desc_fr:   svc?.descripcion_fr              ?? '',
        constructor_nombre:   con ? `${con.nombre ?? ''} ${con.apellido ?? ''}`.trim() || '—' : '—',
        constructor_telefono: con?.telefono ?? '—',
        constructor_email:    con?.email    ?? '—',
        cliente_nombre:       cli ? `${cli.nombre ?? ''} ${cli.apellido ?? ''}`.trim() || '—' : '—',
        direccion:  loc?.direccion  ?? '—',
        provincia:  loc?.provincia  ?? '—',
        canton:     loc?.canton     ?? '—',
        distrito:   loc?.distrito   ?? null,
        precio_final:      c.precio_final,
        garantia_anos:     c.garantia_anos        ?? null,
        plazo_semanas_min: ofe?.plazo_semanas_min ?? null,
        plazo_semanas_max: ofe?.plazo_semanas_max ?? null,
        fecha_inicio:      ofe?.fecha_inicio      ?? '',
        descripcion_trabajo: c.descripcion_trabajo ?? '',
        estado:             c.estado,
        generado_en:        c.generado_en  ?? '',
        firmado_en:         c.firmado_en   ?? null,
        url_pdf:            c.url_pdf      ?? null,
      } as ContratoListItem;
    });
  }

  // ── Buscar contrato existente por expediente ─────────────────────────────

  async buscarPorExpediente(expedienteId: string): Promise<{ id: string; url_pdf: string | null } | null> {
    return this.contratoRepo.findSimpleByExpedienteId(expedienteId);
  }

  async eliminarContrato(contratoId: string, pdfPath: string | null): Promise<void> {
    if (pdfPath) await this.contratoRepo.removePdfFromStorage(pdfPath);
    await this.contratoRepo.deleteById(contratoId);
  }

  async eliminarPdfStorage(pdfPath: string): Promise<void> {
    return this.contratoRepo.removePdfFromStorage(pdfPath);
  }

  async cancelarContrato(expedienteId: string): Promise<void> {
    return this.contratoRepo.cancelar(expedienteId);
  }

  async rechazarOferta(expedienteId: string, ofertaId: string): Promise<void> {
    return this.ofertaRepo.rechazar(expedienteId, ofertaId);
  }

  async cancelarContratoAdmin(contratoId: string): Promise<void> {
    return this.contratoRepo.cancelarAdmin(contratoId);
  }

  async firmarContratoAdmin(contratoId: string): Promise<void> {
    return this.contratoRepo.firmarAdmin(contratoId);
  }

  async iniciarEjecucionContratoAdmin(contratoId: string): Promise<void> {
    return this.contratoRepo.iniciarEjecucionAdmin(contratoId);
  }

  async completarContratoAdmin(contratoId: string): Promise<void> {
    return this.contratoRepo.completarAdmin(contratoId);
  }

  async firmarContrato(contratoId: string): Promise<void> {
    return this.contratoRepo.firmar(contratoId);
  }

  // ── Insertar contrato ────────────────────────────────────────────────────

  async crearContrato(input: ContratoInput): Promise<string> {
    return this.contratoRepo.insert(input);
  }

  async actualizarUrlPdf(contratoId: string, urlPdf: string): Promise<void> {
    return this.contratoRepo.updateUrlPdf(contratoId, urlPdf);
  }

  // ── Storage: PDF ─────────────────────────────────────────────────────────

  async subirPdf(pdfBlob: Blob, contratoId: string): Promise<string> {
    return this.contratoRepo.uploadPdf(pdfBlob, contratoId);
  }

  async getSignedUrl(path: string, expiresInSeconds = 3600): Promise<string> {
    return this.contratoRepo.getSignedUrl(path, expiresInSeconds);
  }

  // ── Admin: detalle de un contrato ────────────────────────────────────────

  async getContratoAdminById(contratoId: string): Promise<ContratoAdminDetalle> {
    const c   = await this.contratoRepo.findDetalleById(contratoId);
    const exp = Array.isArray(c.expediente) ? c.expediente[0] : c.expediente;
    const svc = exp?.servicio    ? (Array.isArray(exp.servicio)    ? exp.servicio[0]    : exp.servicio)    : null;
    const loc = exp?.localizacion ? (Array.isArray(exp.localizacion) ? exp.localizacion[0] : exp.localizacion) : null;
    const cli = Array.isArray(c.cliente)     ? c.cliente[0]     : c.cliente;
    const con = Array.isArray(c.constructor) ? c.constructor[0] : c.constructor;
    const ofe = Array.isArray(c.oferta)      ? c.oferta[0]      : c.oferta;

    let estimadorNombre:    string | null = null;
    let estimadorTelefono:  string | null = null;
    let estimadorEmail:     string | null = null;
    if (exp?.estimador_id) {
      const p = await this.contratoRepo.findPerfilById(exp.estimador_id);
      if (p) {
        estimadorNombre   = `${p.nombre ?? ''} ${p.apellido ?? ''}`.trim() || null;
        estimadorTelefono = p.telefono ?? null;
        estimadorEmail    = p.email    ?? null;
      }
    }

    return {
      id:                   c.id,
      precio_final:         c.precio_final,
      garantia_anos:        c.garantia_anos        ?? null,
      estado:               c.estado,
      generado_en:          c.generado_en          ?? '',
      firmado_en:           c.firmado_en           ?? null,
      url_pdf:              c.url_pdf              ?? null,
      descripcion_trabajo:  c.descripcion_trabajo  ?? '',
      expediente_id:        exp?.id                ?? '',
      expediente_numero:    exp?.numero            ?? '—',
      expediente_estado:    exp?.estado            ?? '',
      servicio_nombre:      svc?.nombre_es         ?? '—',
      servicio_nombre_en:   svc?.nombre_en ?? svc?.nombre_es ?? '—',
      servicio_nombre_fr:   svc?.nombre_fr ?? svc?.nombre_es ?? '—',
      servicio_desc:        svc?.descripcion_es    ?? '',
      servicio_desc_en:     svc?.descripcion_en    ?? '',
      servicio_desc_fr:     svc?.descripcion_fr    ?? '',
      direccion:            loc?.direccion         ?? '—',
      provincia:            loc?.provincia         ?? '—',
      canton:               loc?.canton            ?? '—',
      distrito:             loc?.distrito          ?? null,
      cliente_nombre:       cli ? `${cli.nombre ?? ''} ${cli.apellido ?? ''}`.trim() || '—' : '—',
      cliente_telefono:     cli?.telefono          ?? '—',
      cliente_email:        cli?.email             ?? '—',
      constructor_nombre:   con ? `${con.nombre ?? ''} ${con.apellido ?? ''}`.trim() || '—' : '—',
      constructor_telefono: con?.telefono          ?? '—',
      constructor_email:    con?.email             ?? '—',
      estimador_nombre:     estimadorNombre,
      estimador_telefono:   estimadorTelefono,
      estimador_email:      estimadorEmail,
      oferta_id:            ofe?.id                ?? '',
      oferta_fecha_inicio:  ofe?.fecha_inicio      ?? null,
      plazo_semanas_min:    ofe?.plazo_semanas_min ?? null,
      plazo_semanas_max:    ofe?.plazo_semanas_max ?? null,
    };
  }

  // ── Admin: listar contratos ──────────────────────────────────────────────

  async getContratosAdmin(): Promise<ContratoAdminListItem[]> {
    const rows = await this.contratoRepo.findAllAdmin();

    const estimadorIds = [...new Set(
      rows
        .map((c: any) => {
          const exp = Array.isArray(c.expediente) ? c.expediente[0] : c.expediente;
          return exp?.estimador_id as string | null | undefined;
        })
        .filter((id): id is string => !!id),
    )];

    const perfiles = await this.contratoRepo.findPerfilesByIds(estimadorIds);
    const estimadoresMap: Record<string, string> = {};
    for (const p of perfiles) {
      estimadoresMap[p.id] = `${p.nombre ?? ''} ${p.apellido ?? ''}`.trim();
    }

    return rows.map((c: any) => {
      const exp = Array.isArray(c.expediente) ? c.expediente[0] : c.expediente;
      const svc = exp?.servicio ? (Array.isArray(exp.servicio) ? exp.servicio[0] : exp.servicio) : null;
      const cli = Array.isArray(c.cliente)     ? c.cliente[0]     : c.cliente;
      const con = Array.isArray(c.constructor) ? c.constructor[0] : c.constructor;
      const ofe = Array.isArray(c.oferta)      ? c.oferta[0]      : c.oferta;

      return {
        contrato_id:         c.id,
        precio_final:        c.precio_final,
        garantia_anos:       c.garantia_anos       ?? null,
        contrato_estado:     c.estado,
        generado_en:         c.generado_en         ?? '',
        firmado_en:          c.firmado_en          ?? null,
        expediente_id:       exp?.id               ?? '',
        expediente_numero:   exp?.numero           ?? '—',
        expediente_estado:   exp?.estado           ?? '',
        servicio_nombre:     svc?.nombre_es        ?? '—',
        servicio_nombre_en:  svc?.nombre_en ?? svc?.nombre_es ?? '—',
        servicio_nombre_fr:  svc?.nombre_fr ?? svc?.nombre_es ?? '—',
        cliente_nombre:      cli ? `${cli.nombre ?? ''} ${cli.apellido ?? ''}`.trim() || '—' : '—',
        estimador_nombre:    exp?.estimador_id ? (estimadoresMap[exp.estimador_id] ?? null) : null,
        constructor_nombre:  con ? `${con.nombre ?? ''} ${con.apellido ?? ''}`.trim() || null : null,
        oferta_fecha_inicio: ofe?.fecha_inicio     ?? null,
      } as ContratoAdminListItem;
    });
  }

  // ── PDF generation ────────────────────────────────────────────────────────

  generarPdfBlob(d: ContratoPdfData): Blob {
    const l   = L[d.lang] ?? L['fr'];
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    const W    = 210;
    const PAD  = 18;
    const BODY = W - PAD * 2;
    let   y    = PAD;

    const LINE_COLOR: [number, number, number] = [180, 160, 100];
    const BG_SECTION: [number, number, number] = [245, 242, 234];

    const newPageIfNeeded = (needed = 10) => {
      if (y + needed > 277) { doc.addPage(); y = PAD; }
    };

    const hRule = (thick = false) => {
      doc.setDrawColor(...LINE_COLOR);
      doc.setLineWidth(thick ? 0.5 : 0.25);
      doc.line(PAD, y, W - PAD, y);
      y += 3;
    };

    const sectionHeader = (text: string) => {
      newPageIfNeeded(12);
      doc.setFillColor(...BG_SECTION);
      doc.rect(PAD, y, BODY, 7, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(100, 80, 30);
      doc.text(text, PAD + 3, y + 4.8);
      doc.setTextColor(30, 30, 30);
      y += 10;
    };

    const row = (label: string, value: string, indent = 0) => {
      newPageIfNeeded(7);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(100, 80, 30);
      doc.text(`${label}:`, PAD + indent, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(30, 30, 30);
      const lines = doc.splitTextToSize(value || '—', BODY - 45 - indent);
      doc.text(lines, PAD + 45 + indent, y);
      y += Math.max(lines.length * 5, 5.5);
    };

    const para = (text: string) => {
      if (!text) return;
      newPageIfNeeded(10);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(30, 30, 30);
      const lines = doc.splitTextToSize(text, BODY);
      lines.forEach((line: string) => {
        newPageIfNeeded(6);
        doc.text(line, PAD, y);
        y += 5;
      });
      y += 2;
    };

    // ── HEADER ───────────────────────────────────────────────────────────────
    doc.setFillColor(...LINE_COLOR);
    doc.rect(0, 0, W, 22, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.text(l['title'], W / 2, 10, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(l['subtitle'], W / 2, 16.5, { align: 'center' });
    y = 28;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(50, 50, 50);
    doc.text(`${l['file']}: ${d.expedienteNumero}`, PAD, y);
    doc.text(`${l['date']}: ${d.fechaGenerado}`, W - PAD, y, { align: 'right' });
    y += 6;
    hRule(true);

    // ── PARTIES ──────────────────────────────────────────────────────────────
    sectionHeader(l['parties']);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(60, 60, 60);
    doc.text(l['client'], PAD, y);
    y += 6;
    row(l['clientSign'].split(' ')[1] ?? 'Nom', d.clienteNombre, 3);
    y += 2;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(60, 60, 60);
    doc.text(l['contractor'], PAD, y);
    y += 6;
    row('Nom', d.constructorNombre, 3);
    row(l['phone'], d.constructorTelefono, 3);
    row(l['email'], d.constructorEmail, 3);
    y += 2;
    hRule();

    // ── SERVICE ──────────────────────────────────────────────────────────────
    sectionHeader(l['service']);
    row(l['serviceName'], d.servicioNombre);
    if (d.servicioDescripcion) row(l['description'], d.servicioDescripcion);
    y += 2;
    row(l['address'], d.direccion);
    row('', `${d.canton}  ${d.provincia}  ${d.distrito}`);
    row('', l['country']);
    y += 2;
    hRule();

    // ── TERMS ────────────────────────────────────────────────────────────────
    sectionHeader(l['terms']);
    const precio = new Intl.NumberFormat('fr-CA', {
      style: 'currency', currency: 'CAD', maximumFractionDigits: 0,
    }).format(d.precioFinal);
    row(l['price'], precio);
    if (d.fechaInicio) row(l['start'], d.fechaInicio);
    const plazo = (d.plazoMin || d.plazoMax)
      ? (d.plazoMin === d.plazoMax
          ? `${d.plazoMin} ${l['weeks']}`
          : `${d.plazoMin ?? '?'} – ${d.plazoMax ?? '?'} ${l['weeks']}`)
      : '—';
    row(l['deadline'], plazo);
    const garantia = d.garantiaAnos != null
      ? `${d.garantiaAnos} ${l['years']}`
      : l['noWarranty'];
    row(l['warranty'], garantia);
    y += 2;
    hRule();

    // ── WORK DESCRIPTION ─────────────────────────────────────────────────────
    sectionHeader(l['work']);
    para(d.descripcionTrabajo);
    y += 3;
    hRule();

    // ── SIGNATURES ───────────────────────────────────────────────────────────
    newPageIfNeeded(50);
    sectionHeader(l['signatures']);
    y += 6;
    const col1 = PAD;
    const col2 = W / 2 + 5;
    const sigW = BODY / 2 - 8;
    doc.setDrawColor(100, 100, 100);
    doc.setLineWidth(0.3);
    doc.line(col1, y + 25, col1 + sigW, y + 25);
    doc.line(col2, y + 25, col2 + sigW, y + 25);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(80, 80, 80);
    doc.text(l['clientSign'], col1, y + 30);
    doc.text(l['contractorSign'], col2, y + 30);
    y += 38;
    doc.line(col1, y, col1 + sigW, y);
    doc.line(col2, y, col2 + sigW, y);
    doc.text(l['place'], col1, y + 5);
    doc.text(l['place'], col2, y + 5);

    // ── FOOTER ───────────────────────────────────────────────────────────────
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7);
      doc.setTextColor(160, 140, 80);
      doc.text(
        `${l['generated']}  ·  ${d.contratoId}  ·  ${i}/${pageCount}`,
        W / 2,
        292,
        { align: 'center' },
      );
    }

    return doc.output('blob');
  }
}
