import { Injectable, inject } from '@angular/core';
import jsPDF from 'jspdf';
import { AuthSupabaseService } from './auth-supabase.service';
import { ContratoInput, ContratoPdfData, ContratoListItem } from '../models';

// ── PDF label maps ────────────────────────────────────────────────────────────
const L: Record<string, Record<string, string>> = {
  es: {
    title:       'CONTRATO DE SERVICIOS',
    subtitle:    'Documento generado automáticamente',
    file:        'Expediente',
    date:        'Fecha de generación',
    parties:     'PARTES',
    client:      'CLIENTE',
    contractor:  'CONSTRUCTOR',
    phone:       'Teléfono',
    email:       'Correo',
    service:     'SERVICIO',
    serviceName: 'Tipo de servicio',
    description: 'Descripción',
    address:     'Dirección',
    country:     'CANADÁ',
    terms:       'CONDICIONES DEL CONTRATO',
    price:       'Precio total',
    start:       'Fecha de inicio propuesta',
    deadline:    'Plazo de ejecución',
    warranty:    'Garantía',
    weeks:       'sem.',
    years:       'año(s)',
    noWarranty:  'Sin garantía especificada',
    work:        'DESCRIPCIÓN DE LOS TRABAJOS',
    signatures:  'FIRMAS',
    clientSign:  'Firma del cliente',
    contractorSign: 'Firma del constructor',
    place:       'Lugar y fecha',
    generated:   'Documento generado por el sistema',
  },
  en: {
    title:       'SERVICE CONTRACT',
    subtitle:    'Automatically generated document',
    file:        'File',
    date:        'Generation date',
    parties:     'PARTIES',
    client:      'CLIENT',
    contractor:  'CONTRACTOR',
    phone:       'Phone',
    email:       'Email',
    service:     'SERVICE',
    serviceName: 'Service type',
    description: 'Description',
    address:     'Address',
    country:     'CANADA',
    terms:       'CONTRACT TERMS',
    price:       'Total price',
    start:       'Proposed start date',
    deadline:    'Execution period',
    warranty:    'Warranty',
    weeks:       'wks.',
    years:       'year(s)',
    noWarranty:  'No warranty specified',
    work:        'DESCRIPTION OF WORK',
    signatures:  'SIGNATURES',
    clientSign:  'Client signature',
    contractorSign: 'Contractor signature',
    place:       'Place and date',
    generated:   'Document generated by the system',
  },
  fr: {
    title:       'CONTRAT DE SERVICES',
    subtitle:    'Document généré automatiquement',
    file:        'Dossier',
    date:        'Date de génération',
    parties:     'PARTIES',
    client:      'CLIENT',
    contractor:  'CONSTRUCTEUR',
    phone:       'Téléphone',
    email:       'Courriel',
    service:     'SERVICE',
    serviceName: 'Type de service',
    description: 'Description',
    address:     'Adresse',
    country:     'CANADA',
    terms:       'CONDITIONS DU CONTRAT',
    price:       'Prix total',
    start:       'Date de début proposée',
    deadline:    "Délai d'exécution",
    warranty:    'Garantie',
    weeks:       'sem.',
    years:       'an(s)',
    noWarranty:  'Aucune garantie spécifiée',
    work:        'DESCRIPTION DES TRAVAUX',
    signatures:  'SIGNATURES',
    clientSign:  'Signature du client',
    contractorSign: 'Signature du constructeur',
    place:       'Lieu et date',
    generated:   'Document généré par le système',
  },
};

@Injectable({ providedIn: 'root' })
export class ContratoService {
  private auth = inject(AuthSupabaseService);
  private get db() { return this.auth.client; }

  // ── Supabase: listar contratos del cliente ────────────────────────────────

  async getMisContratos(clienteId: string): Promise<ContratoListItem[]> {
    const { data, error } = await this.db
      .from('contrato')
      .select(`
        id, precio_final, garantia_anos, estado, generado_en, url_pdf, descripcion_trabajo,
        expediente:expediente_id (
          numero,
          servicio:servicio_id ( nombre_es, nombre_en, nombre_fr, descripcion_es, descripcion_en, descripcion_fr ),
          localizacion ( direccion, provincia, canton, distrito )
        ),
        constructor:constructor_id ( nombre, apellido, telefono, email ),
        cliente:cliente_id ( nombre, apellido ),
        oferta:oferta_id ( plazo_semanas_min, plazo_semanas_max, fecha_inicio )
      `)
      .eq('cliente_id', clienteId)
      .order('generado_en', { ascending: false });

    if (error) throw new Error(error.message);

    return (data ?? []).map((c: any) => {
      const svc = c.expediente?.servicio;
      const locArr = c.expediente?.localizacion;
      const loc = Array.isArray(locArr) ? locArr[0] : locArr;
      const con = c.constructor;
      const cli = c.cliente;
      const ofe = Array.isArray(c.oferta) ? c.oferta[0] : c.oferta;
      return {
        id:                 c.id,
        expediente_numero:  c.expediente?.numero             ?? '—',
        servicio_nombre:    svc?.nombre_es                   ?? '—',
        servicio_nombre_en: svc?.nombre_en ?? svc?.nombre_es ?? '—',
        servicio_nombre_fr: svc?.nombre_fr ?? svc?.nombre_es ?? '—',
        servicio_desc:      svc?.descripcion_es              ?? '',
        servicio_desc_en:   svc?.descripcion_en              ?? '',
        servicio_desc_fr:   svc?.descripcion_fr              ?? '',
        constructor_nombre:   con ? `${con.nombre ?? ''} ${con.apellido ?? ''}`.trim() || '—' : '—',
        constructor_telefono: con?.telefono ?? '—',
        constructor_email:    con?.email    ?? '—',
        cliente_nombre:       cli ? `${cli.nombre ?? ''} ${cli.apellido ?? ''}`.trim() || '—' : '—',
        direccion:  loc?.direccion  ?? '—',
        provincia:  loc?.provincia  ?? '—',
        canton:     loc?.canton     ?? '—',
        distrito:   loc?.distrito   ?? null,
        precio_final:      c.precio_final,
        garantia_anos:     c.garantia_anos        ?? null,
        plazo_semanas_min: ofe?.plazo_semanas_min ?? null,
        plazo_semanas_max: ofe?.plazo_semanas_max ?? null,
        fecha_inicio:      ofe?.fecha_inicio      ?? '',
        descripcion_trabajo: c.descripcion_trabajo ?? '',
        estado:             c.estado,
        generado_en:        c.generado_en ?? '',
        url_pdf:            c.url_pdf     ?? null,
      } as ContratoListItem;
    });
  }

  // ── Supabase: buscar contrato existente ──────────────────────────────────

  async buscarPorExpediente(expedienteId: string): Promise<{ id: string; url_pdf: string | null } | null> {
    const { data, error } = await this.db
      .from('contrato')
      .select('id, url_pdf')
      .eq('expediente_id', expedienteId)
      .maybeSingle();
    if (error) throw new Error(error.message);
    return data as { id: string; url_pdf: string | null } | null;
  }

  async eliminarContrato(contratoId: string, pdfPath: string | null): Promise<void> {
    if (pdfPath) {
      await this.db.storage.from('contratos').remove([pdfPath]);
    }
    const { error } = await this.db
      .from('contrato')
      .delete()
      .eq('id', contratoId);
    if (error) throw new Error(error.message);
  }

  async eliminarPdfStorage(pdfPath: string): Promise<void> {
    await this.db.storage.from('contratos').remove([pdfPath]);
  }

  async cancelarContrato(expedienteId: string): Promise<void> {
    const { error } = await (this.db.rpc as any)('cancelar_contrato', { p_expediente_id: expedienteId });
    if (error) throw new Error(error.message);
  }

  // ── Supabase: insertar contrato ───────────────────────────────────────────

  async crearContrato(input: ContratoInput): Promise<string> {
    const { data, error } = await this.db
      .from('contrato')
      .insert({
        expediente_id:       input.expediente_id,
        oferta_id:           input.oferta_id,
        cliente_id:          input.cliente_id,
        constructor_id:      input.constructor_id,
        precio_final:        input.precio_final,
        garantia_anos:       input.garantia_anos,
        descripcion_trabajo: input.descripcion_trabajo,
        estado:              'generado',
      })
      .select('id')
      .single();

    if (error) throw new Error(error.message);
    return (data as any).id as string;
  }

  async actualizarUrlPdf(contratoId: string, urlPdf: string): Promise<void> {
    const { error } = await this.db
      .from('contrato')
      .update({ url_pdf: urlPdf })
      .eq('id', contratoId);
    if (error) throw new Error(error.message);
  }

  // ── Supabase Storage: subir PDF ───────────────────────────────────────────

  async subirPdf(pdfBlob: Blob, contratoId: string): Promise<string> {
    const path = `${contratoId}.pdf`;
    const { error } = await this.db.storage
      .from('contratos')
      .upload(path, pdfBlob, { contentType: 'application/pdf', upsert: false });
    if (error) throw new Error(error.message);
    return path;
  }

  async getSignedUrl(path: string, expiresInSeconds = 3600): Promise<string> {
    const { data, error } = await this.db.storage
      .from('contratos')
      .createSignedUrl(path, expiresInSeconds);
    if (error) throw new Error(error.message);
    return data.signedUrl;
  }

  // ── PDF generation ────────────────────────────────────────────────────────

  generarPdfBlob(d: ContratoPdfData): Blob {
    const l   = L[d.lang] ?? L['fr'];
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    const W    = 210;
    const PAD  = 18;
    const BODY = W - PAD * 2;
    let   y    = PAD;

    const LINE_COLOR: [number, number, number] = [180, 160, 100];
    const BG_SECTION: [number, number, number] = [245, 242, 234];

    // ── helpers ──────────────────────────────────────────────────────────────
    const newPageIfNeeded = (needed = 10) => {
      if (y + needed > 277) { doc.addPage(); y = PAD; }
    };

    const hRule = (thick = false) => {
      doc.setDrawColor(...LINE_COLOR);
      doc.setLineWidth(thick ? 0.5 : 0.25);
      doc.line(PAD, y, W - PAD, y);
      y += 3;
    };

    const sectionHeader = (text: string) => {
      newPageIfNeeded(12);
      doc.setFillColor(...BG_SECTION);
      doc.rect(PAD, y, BODY, 7, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(100, 80, 30);
      doc.text(text, PAD + 3, y + 4.8);
      doc.setTextColor(30, 30, 30);
      y += 10;
    };

    const row = (label: string, value: string, indent = 0) => {
      newPageIfNeeded(7);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(100, 80, 30);
      doc.text(`${label}:`, PAD + indent, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(30, 30, 30);
      const lines = doc.splitTextToSize(value || '—', BODY - 45 - indent);
      doc.text(lines, PAD + 45 + indent, y);
      y += Math.max(lines.length * 5, 5.5);
    };

    const para = (text: string) => {
      if (!text) return;
      newPageIfNeeded(10);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(30, 30, 30);
      const lines = doc.splitTextToSize(text, BODY);
      lines.forEach((line: string) => {
        newPageIfNeeded(6);
        doc.text(line, PAD, y);
        y += 5;
      });
      y += 2;
    };

    // ── HEADER ───────────────────────────────────────────────────────────────
    doc.setFillColor(...LINE_COLOR);
    doc.rect(0, 0, W, 22, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.text(l['title'], W / 2, 10, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(l['subtitle'], W / 2, 16.5, { align: 'center' });

    y = 28;

    // File + date
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(50, 50, 50);
    doc.text(`${l['file']}: ${d.expedienteNumero}`, PAD, y);
    doc.text(`${l['date']}: ${d.fechaGenerado}`, W - PAD, y, { align: 'right' });
    y += 6;
    hRule(true);

    // ── PARTIES ──────────────────────────────────────────────────────────────
    sectionHeader(l['parties']);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(60, 60, 60);
    doc.text(l['client'], PAD, y);
    y += 6;
    row(l['clientSign'].split(' ')[1] ?? 'Nom', d.clienteNombre, 3);
    y += 2;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(60, 60, 60);
    doc.text(l['contractor'], PAD, y);
    y += 6;
    row('Nom', d.constructorNombre, 3);
    row(l['phone'], d.constructorTelefono, 3);
    row(l['email'], d.constructorEmail, 3);
    y += 2;
    hRule();

    // ── SERVICE ──────────────────────────────────────────────────────────────
    sectionHeader(l['service']);
    row(l['serviceName'], d.servicioNombre);
    if (d.servicioDescripcion) row(l['description'], d.servicioDescripcion);
    y += 2;
    row(l['address'], d.direccion);
    row('', `${d.canton}  ${d.provincia}  ${d.distrito}`);
    row('', l['country']);
    y += 2;
    hRule();

    // ── TERMS ────────────────────────────────────────────────────────────────
    sectionHeader(l['terms']);

    const precio = new Intl.NumberFormat('fr-CA', {
      style: 'currency', currency: 'CAD', maximumFractionDigits: 0,
    }).format(d.precioFinal);
    row(l['price'], precio);

    if (d.fechaInicio) row(l['start'], d.fechaInicio);

    const plazo = (d.plazoMin || d.plazoMax)
      ? (d.plazoMin === d.plazoMax
          ? `${d.plazoMin} ${l['weeks']}`
          : `${d.plazoMin ?? '?'} – ${d.plazoMax ?? '?'} ${l['weeks']}`)
      : '—';
    row(l['deadline'], plazo);

    const garantia = d.garantiaAnos != null
      ? `${d.garantiaAnos} ${l['years']}`
      : l['noWarranty'];
    row(l['warranty'], garantia);
    y += 2;
    hRule();

    // ── WORK DESCRIPTION ─────────────────────────────────────────────────────
    sectionHeader(l['work']);
    para(d.descripcionTrabajo);
    y += 3;
    hRule();

    // ── SIGNATURES ───────────────────────────────────────────────────────────
    newPageIfNeeded(50);
    sectionHeader(l['signatures']);
    y += 6;

    const col1 = PAD;
    const col2 = W / 2 + 5;
    const sigW = BODY / 2 - 8;

    doc.setDrawColor(100, 100, 100);
    doc.setLineWidth(0.3);

    // Signature lines
    doc.line(col1, y + 25, col1 + sigW, y + 25);
    doc.line(col2, y + 25, col2 + sigW, y + 25);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(80, 80, 80);
    doc.text(l['clientSign'], col1, y + 30);
    doc.text(l['contractorSign'], col2, y + 30);

    y += 38;
    doc.line(col1, y, col1 + sigW, y);
    doc.line(col2, y, col2 + sigW, y);
    doc.text(l['place'], col1, y + 5);
    doc.text(l['place'], col2, y + 5);

    // ── FOOTER ───────────────────────────────────────────────────────────────
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7);
      doc.setTextColor(160, 140, 80);
      doc.text(
        `${l['generated']}  ·  ${d.contratoId}  ·  ${i}/${pageCount}`,
        W / 2,
        292,
        { align: 'center' },
      );
    }

    return doc.output('blob');
  }
}
